name = "packages_echocat_org"
main = "src/index.ts"
compatibility_date = "2023-12-19"
account_id = "eae269e15c934608f8593a46c8628bcc"

kv_namespaces = [
    { binding = "KV", id = "2aebe3f8f0b7463397f06cf498d082fa", preview_id = "194372f42e834b6ca81e0dd188bb59d1" }
]

node_compat = true

[vars]
GITHUB_ACCESS_USER = "echocatbot"

[triggers]
crons = [ "0 */2 * * *" ]
